//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentBill
    {
        public int buildingCode { get; set; }
        public string flatNumber { get; set; }
        public string datestart { get; set; }
        public string dateend { get; set; }
        public string unitAmount { get; set; }
        public string totalAmount { get; set; }
        public string status { get; set; }
        public int id { get; set; }
    }
}
