//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class subUser
    {
        public int id { get; set; }
        public int colonyCode { get; set; }
        public int buildingCode { get; set; }
        public string flatNumber { get; set; }
        public string mobile { get; set; }
        public string usertype { get; set; }
    }
}
